random_seed: 41
train_set_size: 0.6
test_set_size: 0.5
source:
  path: /../../data/
sink:
  default: ../sink
  path: ../../sink/
  csv:
    sep: ;
    encoding: utf-8
    mode: a
    header: False
    index: False
  suffix: .csv
cache:
  default: ../cache
data:
  default: ../data
models:
  default: ../models
logs:
  path: ../logs
  level: INFO