random_seed: 42
train_set_size: 0.6
test_set_size: 0.5
class_names:
  - negative
  - neutral
  - positive
strategies:
  - multi_noger
  - multi_all
  - ger_only
  - multi_noenglish
  - multi_noarabic
  - multi_nodutch
  - multi_nofrench
  - multi_nochinese
  - multi_nopolish
pre_trained_model_name: bert-base-multilingual-cased
batch_size: 32
max_len: 256
epochs: 3
learning_rate: 0.00002
num_workers: 4
correct_bias: False
num_warmup_steps: 0
dropout_ratio: 0.3
shuffle: True
source:
  path: /../../data/
sink:
  default: ../sink
  path: ../../sink/
  csv:
    sep: ;
    encoding: utf-8
    mode: a
    header: False
    index: False
  suffix: .csv
cache:
  default: ../cache
data:
  default: ../data
models:
  default: ../models
logs:
  path: ../logs
  level: INFO